### ISSUE TITLE
[FEATURE] Split file naming

### ISSUE THREAD

**Issue by gquintana** [elasticsearch-dump/elasticsearch-dump#1063]
**Is your feature request related to a problem? Please describe.**
Files generated when `--fileSize` argument is set can not be easily sorted:
```
activity.data.split-0.json.gz
activity.data.split-1.json.gz
activity.data.split-10.json.gz
activity.data.split-11.json.gz
```

**Describe the solution you'd like**
I would like left padding in split numbering
```
activity.data.split-00000.json.gz
activity.data.split-00001.json.gz
activity.data.split-00002.json.gz
activity.data.split-00003.json.gz
```

Moreover, let's say I am running elasticdump with following options:
```
elasticdump (...) --type data --output s3://mybucket/myfolder/activity.data.json.gz --s3Compress --limit 1000
```
As expected, I get a file named  `activity.data.json.gz`
Then I enable file splitting
```
elasticdump (...) --type data --output s3://mybucket/myfolder/activity.data.json.gz --s3Compress --limit 1000 --fileSize 1gb
```
Then I get files named
```
activity.data.json.split-0.gz.gz
```
So I have to remove the `.gz` to get what I want:
```
elasticdump (...) --type data --output s3://mybucket/myfolder/activity.data.json --s3Compress --limit 1000 --fileSize 1gb
```
Personnally, when compress is enabled, I would remove the trailing `.gz` [here](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/splitters/streamSplitter.js#L32) in order to get the `.json` extension, and then I would add it back [here](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/splitters/streamSplitter.js#L32).

Another option would be to add the `.gz` extension when compression is enabled but file splitting is disabled.

**Comment by ferronrsmith** [comment]
All good ideas, but not that useful for this library. Feel free to fork.

Left padding limits to 4 digits, which means you have a max of 9999, I have seen more splits been done, this logic can work for you. i have no problem sort using bash `ls -1 | sort ....`

You don't need to include the extension at the end since it will be added at the library. Yes I can detect and strip, but this is really just nit-picking.

 
elasticdump (...) --type data --output s3://mybucket/myfolder/activity.data.json --s3Compress --limit 1000 --fileSize 1gb
