### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by evantahler** [elasticsearch-dump/elasticsearch-dump#11]
threads, forks, something...

**Comment by geekpete** [comment]
Yeah I think that general principle will work.

So just run more than one scroll simultaneously, this way each scroll could have a separate elasticdump running against it.

The separate scrolls will be queries that chop the total doc set into separate segments to be processed simultaneously.

If they're all started simultanously, then it will capture a single point in time across the total set of documents (more or less), since each document from that point in time will be marked to be kept until the scrolls are finished.

So the question is if doing this in parallel scales and if so by how much.

It should, so to try it take a data set and work out how to divide the documents (time based or whatever).

What do you rekon?

**Comment by evantahler** [comment]
It seems like a good idea in practice, but would need a fair amount of testing!

**Comment by snikch** [comment]
ID's could be a good solution for this. If you have evenly(ish) distributed identifiers, these could be used to create discrete scroll's, such as dividing UUID's by character, or auto incrementing ID's given an approx range of the dataset.

**Comment by evantahler** [comment]
Regardless of if you are using INTs, Strings, or UUIDs (built into ElasticSearch) I guess either way you could first get a 'range' of all of them in one huge query, parse them out, and distribute them.    This would be pretty slow though.

We might also do a "first letter" type query, wherin you partition the export by all possible UTF8 characters, and then assign them to each extractor in a round-robin style

**Comment by geekpete** [comment]
We are looking to use an arbitrary field with a randomly generated number between 1 and 100 for each document.

This way we can do a reindex using a scroll with a query that manually shards the docs based on this field and potentially could run 100 concurrent reindex scrolls at once if the cluster can handle that.

Also allows less concurrent reindex scrolls easily by doing a modulo of that field, eg query where value of that field is 1-20 or 21-40 or,etc for 5 concurrent scrolls.

A new upcoming feature of elasticsearch will allow an online reindex at server side in the background which will chug away until it's done, cutting the alias over at the end and keeping everything consistent including updates that happen since the reindex is kicked off, but need to see if this is exactly how that feature will work.

**Comment by shaharmor** [comment]
You can parallelize by index/type

**Comment by TheDeveloper** [comment]
I dropped an [issue](https://github.com/elastic/elasticsearch/issues/14954) in the elasticsearch repo about parallelising scan/scroll.

Since that's not currently possible, it seems the best way is to shard up the data somehow and use a separate scan/scroll session for each chunk concurrently. Exactly how this is done depends on the data itself, but I've seen some good suggestions here: by ID, index/type, or if you have time series, by timestamp.

Perhaps sharding and job-coordination could be built as another module.

**Comment by evantahler** [comment]
I think the hardest part of "parallelization scheduling" is that in order to see any real gains, we must use multiple computers running this tool.  Assuming your ES cluster's disk speed and bandwidth is faster than that of your ElasticDump node, running just one dump would saturate *something* on the downstream end (IO).  Running more than one dump in parallel at best would slow each dump down linearly and the total dump time would be the same as running N in series.  However, that's rarely the case, and it will probably be worse (CPU swapping, disk contention, etc).

If your ES cluster's resources are worse of than your dump nodes, than you will likely hurt the performance of your cluster by dumping in parallel, as you would be essentially asking the cluster to spend all of its resources on these dumps.

So ignoring the second case (or hoping that you would only dump a cluster described in .2 in an offline case), the only way to see gains would host parallelization.  So now we need *mq, redis, a special index within elasticsearch to store state... something like that.

**Comment by geekpete** [comment]
I wrote a reindex script in python using the elasticsearch python library that includes a basic reindex helper function that can reindex based on a query. It only goes from cluster to cluster, but I have it successfully doing 56k docs/sec on our large cluster.

It hinges on a field in my particular schema that allows me to split the docs I want to reindex so that I can run 10 concurrent scrolls. My script uses a work queue and threads.

**Comment by geekpete** [comment]
Also if you have a workable timestamp field then you can just reindex the whole data set and keep track of the start time of the scroll, then reindex all docs that have changed since that timestamp, and repeat until the number of docs is sufficiently small to pause inbound updates to complete the last small reindex.

**Comment by geekpete** [comment]
And with saturation, on sufficiently large production clusters and machines this is less of an issue. Fast SSD raid disks on servers with 1gig or 10gig networks should be fine for a large disk dump and any cluster that you want to perform well has to have enough grunt anyway. But a valid point that your cluster might be ok for your normal workload but reindexing in parallel might push it to the limit, so this is when tuning how many concurrent threads can process should be tuneable. You'd probably not want to queue any chunks of the sharded work up, you'd instead shard the work into less chunks and still process it simultaneously for as much consistency as possible.

**Comment by royrusso** [comment]
A relevant side not here is maybe to investigate how the elasticsearch-hadoop library works under the hood. That library, running inside of Apache Spark, connects directly to individual shards to query on, thus parallelizing the workload. More here: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/arch.html

**Comment by ebuildy** [comment]
Hey guys, any new about that ?

For now I am using ``/_search_shards?preference=_primary`` API to retrieve shards/nodes map, and spawn ``elasticsearch-dump`` process for each, work quite good, but this could be implemented inside this program maybe?

**Comment by geekpete** [comment]
Elasticsearch 5.0 now has the new Sliced Scroll feature that allows a scroll to be divided into "slices" that then allows you to use multiple threads to process a single scroll:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#sliced-scroll

This solves the problem neatly.

Scroll slicing can be used against reindexing, delete-by-query and update workloads. 

It still has limits, your cluster resources will inform how many slices you can use before hammering your cluster performance generally due to the overhead incurred from creating each scroll slice

Speed improvements of multi-threaded sliced scroll over a single thread using a single scroll id should be very significant.

**Comment by ebuildy** [comment]
Very nice !

**Comment by LordMike** [comment]
It is also possible to specify specific shards in the search queries: (`_shards:X`) https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html

This should allow you to (with ES as input):
* Query the number of shards for an index
* Spawn N parallel queries, each targeting 1 shard

**Comment by ebuildy** [comment]
Doing the scroll from each shards is the best way to do that, the plugin (from Elastic) elasticsearch4hadoop works this way.
1- Get how many shards the index have
2- Search scroll in parallel  from each

**Comment by fedeisas** [comment]
Slightly off topic, but I've been trying to find ways to speed up my read-transform-write processes. With the [new sliced-scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#sliced-scroll) it's easy to parallelize reading. I'm wondering how to decouple read/write threads so I can have a steady reading stream (scrolling every _XXX_ ms), use local memory as a temporary buffer, and `_bulk` as fast as I can without blocking reads.

Does anyone knows if there's a limit on how many `_bulk` requests can be sent concurrently?
