### ISSUE TITLE
[BUG] Unable to resolve DNS randomly during the copy

### ISSUE THREAD

**Issue by gmelillo** [elasticsearch-dump/elasticsearch-dump#738]
**Context**
To help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: `6.33.4`
- Elasticsearch version: `7.9`
- Node.js version *(note that nodejs v10+ is required for this tool)*: `v12.19.0`
- Full command you are having issue with (with inputs and outputs): Note relevant for the issue
- A data-set you can share publicly which reproduces the problem: Note relevant for the issue

**Describe the bug**

During a data migration to the AWS ElasticSearch domain, we hit a lot of errors due to NXDOMAIN.
For some reason when you have a DNS record that is resolving 20 IPs for round-robin the docker image starts to fail.

**To Reproduce**

1. Create a new cluster in AWS with 20 nodes
2. Try to copy some data using the image

(in our case the container was running on AWS EKS)

**Current behavior**

The application is unable to process the migration due to NXDOMAIN

Error example:

```
Thu, 12 Nov 2020 02:57:18 GMT | Error Emitted => getaddrinfo ENOTFOUND es-domain.eu-west-1.es.amazonaws.com
Thu, 12 Nov 2020 02:57:18 GMT | Error Emitted => getaddrinfo ENOTFOUND es-domain.eu-west-1.es.amazonaws.com
dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND es-domain.eu-west-1.es.amazonaws.com
```

**Expected behavior**

The application will copy the data from start to end

**Additional context**

During the debug we pinpointed the issue to possibly be in the alpine subsystem and we fixed it by rebuilding the docker image using Ubuntu as the base image.

**Suggested change**

To mitigate this issue in the future, an image based on Ubuntu/Debian will be helpful to have.
I can also open a PR to move to the Ubuntu/Debian based image.

**Comment by ferronrsmith** [comment]
This isn't a bug, it's a network issue which can't be diagnosed based on the information provided.

It could that your sending requests too fast and the endpoint is return a DOS, try throttling requests, if that doesn't work there is a retry param with variable back off. Beyond that there isn't much I can advice since the network layer isn't something this library controls

**Comment by gmelillo** [comment]
@ferronrsmith The issue is, in fact, in the Linux Alpine used as a base layer [here](https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/Dockerfile#L1)

**Comment by ferronrsmith** [comment]
I know alpine is notorious for having network issues with musl, but I've not experienced this myself. I don't really want to be hacking docker images, I'll see if it's feasible to change the base image. I might have to generate 2 docker images, since alpine is nice for environments with limited resources

**Comment by ferronrsmith** [comment]
Switched to `buster-slim`. The image is currently building. Alpine isn't worth the trouble and the images are just 20 mb in size difference
