### ISSUE TITLE
 migrate data from A cluster to cluster B, Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by 3tem** [elasticsearch-dump/elasticsearch-dump#766]
Es ：6.2.2
docker images : elasticdump/elasticsearch-dump:latest

I have two use k8s es cluster deployment, I use NodePort exposed the port，I now need to migrate data from A cluster to cluster B,
elasticsearch-dump  info: 
docker run --rm -ti af.hikvision.com.cn/docker-fireprotection/elasticsearch-dump:latest \
  --input=http://10.2.3.21:31920 /monitor_history_copy \
  --output=http://10.2.3.29:31920/monitor_history_copy_copy \
  --type=data

 error:  Mon, 01 Feb 2021 11:42:41 GMT | dump ended with error (get phase) => Error: connect ETIMEDOUT 10.23.3.29:31920

 but i user  curl http://10.2.3.29:31920/monitor_history_copy_copy  is ok

**Comment by ferronrsmith** [comment]
This could be caused by ES being unresponsive during index caused by resource starvation. 

There isn't enough information here to know what the issue is. You can try increasing the retry limit and retryDelay to compensate for the period of downtime. Although 100 records shouldn't be caused this issue, but then I don't know how elasticsearch is configured

**Comment by 3tem** [comment]
ok,i try.
