### ISSUE TITLE
Dump only latest or newest rolled over index.

### ISSUE THREAD

**Issue by archfz** [elasticsearch-dump/elasticsearch-dump#791]
**Is your feature request related to a problem? Please describe.**
I am trying to multi dump every index mapping and settings. The issues is that I have rollover configured, and thus have many basically duplicated indexes. It would be nice if it was possible to only dump the oldest from the same types of indexes. I couldn't figure out a way to do this with the --match.

**Describe the solution you'd like**
Functionality to recognize same index rolled over indexes and only dump settings / mapping from the first or last one.

**Describe alternatives you've considered**
--match but no regex can cover this.

**Comment by ferronrsmith** [comment]
Regex isn't the right tool for this. You need something to compare dates. I'm not going to add this feature because it's too specific and this isn't the type of library for this. 

What I can do is expose a filter function that can be applied to the matchIndexes to perform further filter based on a predefined user function.



```javascript


matchIndex = []

// with a module at ./filters/roll-over.js with the following:

module.exports = function (indexes) {
    // do something to doc
};
```

**Comment by archfz** [comment]
In that case can close this issue. I will write post processing shellscript to remove the duplicates. It would have been nice to have this builtin to reduce export time. But since its not a regular thing the time is not that important.

**Comment by ferronrsmith** [comment]
I think you're missing the point. It's all about making things generic so that it can be useful to other people, not just your specific needs. It would allow you to apply any filter function list matched indices, which I think is a bit more powerful that what you suggested. Because you can do expression based filtering, condition based filtering etc.

**Comment by archfz** [comment]
Yeah but in that case wait and see if there is more need for this. Not worth implementing only for my specific case.

**Comment by ferronrsmith** [comment]
Not exactly, but if you want to go at it the `bash way` that's fine. All the best
