### ISSUE TITLE
[BUG] From and size in searchbody is ignored

### ISSUE THREAD

**Issue by jastax** [elasticsearch-dump/elasticsearch-dump#796]
**Context**

- ElasticDump version  6.69.2
- Elasticsearch version 6.8.14
- Node.js version v14.15.3

**Describe the bug**
I'd like to get a limited set of data starting at x (i.e. 0) and a certain size y (i.e. 1). I figured that I need to use from and size in the searchbody.

For example:

`elasticdump  --input=http://myurl.com --output=ex_data.json--searchBody='{\"from\":\"0\", \"size\":\"1\"}'`

Both parameters seem to be ignored and the data is dumped in blocks of 100 until I stop the script.

I've found the same behaviour on Linux and Windows.  Is there another way to do this?

**Comment by ferronrsmith** [comment]
Offset is no longer supported by ES and **size** should be **limit**

**Comment by ferronrsmith** [comment]
`from` is support in search requests. elasticdump does a scroll request. This hasn't been supported since ES 6 (breaking change)
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_scroll

The size can be configured, but remember. Size in scroll is different from search.

> The **size** parameter allows you to configure the maximum number of hits to be returned with each batch of results.

**Comment by jastax** [comment]
Thanks, that's helpful :)
